language: ruby
rvm:
- 2.2.5
script: scripts/build.sh
install: gem install jekyll html-proofer jekyll-sitemap
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_ADR=deploy@bot.nickvorobiov.com:/var/www/x3.ocheredklientov.com
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: gh-pages
